package spg

/**
 * Secure Password Generator.
 *
 * Lovingly handcrafted by Dave Teare on October 20th, 2017
 * Cruelly butchered by Jeffrey Goldberg in February 2018
 */

/** Attributes

	Attributes are all of the knobs that can be set for specifying details of what
	of the password requirements.

	There are two kinds of attributes (other than the Length). There are those that are
	specific for character type passwords and those that are relevant to things based
	on word lists. Ultimately we are sticking this all in the same type so that we
	can have a common Generator interface. So this gets kind of messy
 **/

// Password is what gets generated by the Generators
type Password struct {
	Tokens []Token
	ent    float32 // The strength of the generated password in bits.
}

// Entropy returns the strength of the generated password
func (p Password) Entropy() float32 { return p.ent }
